# **1. Array Creation**

In [1]:
import numpy as np

In [6]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
# Create an array filled with zeros
zeros_arr = np.zeros((3, 3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Create an array filled with ones
ones_arr = np.ones((2, 4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# Create an array filled with a specific value
full_arr = np.full((2, 3), 7)
full_arr

array([[7, 7, 7],
       [7, 7, 7]])

In [9]:
# Create an identity matrix
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# Create an array with evenly spaced values within a given range
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [12]:
# Create an array with evenly spaced numbers over a specified interval
linspace_arr = np.linspace(0, 1, 5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Create an array with values that are logarithmically spaced
logspace_arr = np.logspace(0, 3, 4)
logspace_arr

array([   1.,   10.,  100., 1000.])

# **2. Array Manipulation**

In [14]:
# Reshape the array
reshaped_arr = arr.reshape((5, 1))
reshaped_arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
# Flatten the array
flattened_arr = reshaped_arr.ravel()
flattened_arr

array([1, 2, 3, 4, 5])

In [16]:
# Transpose the array
transposed_arr = np.transpose(reshaped_arr)
transposed_arr

array([[1, 2, 3, 4, 5]])

In [17]:
# Concatenate two arrays
concatenated_arr = np.concatenate((arr, arr))
concatenated_arr

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [18]:
# Stack arrays along a new axis
stacked_arr = np.stack((arr, arr))
stacked_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [19]:
# Split the array into multiple sub-arrays
split_arr = np.split(arr, 5)
split_arr

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [20]:
# Expand dimensions
expanded_arr = np.expand_dims(arr, axis=1)
expanded_arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
# Squeeze dimensions
squeezed_arr = np.squeeze(expanded_arr)
squeezed_arr

array([1, 2, 3, 4, 5])

# **3. Array Operations**

In [22]:
# Element-wise addition
add_arr = np.add(arr, arr)
add_arr

array([ 2,  4,  6,  8, 10])

In [23]:
# Element-wise subtraction
sub_arr = np.subtract(arr, arr)
sub_arr

array([0, 0, 0, 0, 0])

In [24]:
# Element-wise multiplication
mul_arr = np.multiply(arr, arr)
mul_arr

array([ 1,  4,  9, 16, 25])

In [25]:
# Element-wise division
div_arr = np.divide(arr, arr)
div_arr

array([1., 1., 1., 1., 1.])

In [26]:
# Dot product of two arrays
dot_product = np.dot(arr, arr)
dot_product

55

In [27]:
# Compute the mean of array elements
mean_value = np.mean(arr)
mean_value

3.0

In [28]:
# Compute the sum of array elements
sum_value = np.sum(arr)
sum_value

15

In [29]:
# Compute the minimum of array elements
min_value = np.min(arr)
min_value

1

In [30]:
# Sort the array elements
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

# **4. Linear Algebra**

In [32]:
# Inverse of a matrix
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
determinant

-2.0000000000000004

In [36]:
# Eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [37]:
# Solve a linear matrix equation
solution = np.linalg.solve(matrix, np.array([1, 2]))
solution

array([0. , 0.5])

# **5. Fourier Transform**

In [39]:
# One-dimensional discrete Fourier Transform
fft_result = np.fft.fft(arr)
fft_result

array([15. +0.j        , -2.5+3.4409548j , -2.5+0.81229924j,
       -2.5-0.81229924j, -2.5-3.4409548j ])

In [40]:
# Inverse discrete Fourier Transform
ifft_result = np.fft.ifft(fft_result)
ifft_result

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

# **6. Random Number Generation**

In [42]:
# Generate random floats
random_floats = np.random.random((2, 2))
random_floats

array([[0.50431659, 0.47354234],
       [0.13086532, 0.56782472]])

In [43]:
# Generate random integers
random_integers = np.random.randint(0, 10, (2, 2))
random_integers

array([[2, 1],
       [1, 6]])

In [44]:
# Generate random integers
random_integers = np.random.randint(0, 10, (2, 2))
random_integers

array([[9, 9],
       [6, 3]])

# **7. Statistics and Probability**

In [45]:
# Compute the median
median_value = np.median(arr)
median_value

3.0

In [46]:
# Compute the standard deviation
std_dev = np.std(arr)
std_dev

1.4142135623730951

In [47]:
# Compute the variance
variance = np.var(arr)
variance

2.0

In [50]:
# Generate a histogram of data
hist, bin_edges = np.histogram(arr)
print(hist)
print(bin_edges)

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1])

# **8. Trigonometric Functions**

In [60]:
# Compute the sine
sine_values = np.sin(arr)
sine_values

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [61]:
# Compute the cosine
cosine_values = np.cos(arr)
cosine_values

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [62]:
# Compute the tangent
tangent_values = np.tan(arr)
tangent_values

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

# **9. Exponential and Logarithmic Functions**

In [57]:
# Compute the exponential
exp_values = np.exp(arr)
exp_values

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [58]:
# Compute the natural logarithm
log_values = np.log(arr)
log_values

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [59]:
# Compute the base-10 logarithm
log10_values = np.log10(arr)
log10_values

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

# **10. Miscellaneous**

In [54]:
# Copy an array
copied_arr = np.copy(arr)
copied_arr

array([1, 2, 3, 4, 5])

In [55]:
# Find the unique elements of an array
unique_elements = np.unique(arr)
unique_elements

array([1, 2, 3, 4, 5])

In [56]:
# Test for NaN values
nan_check = np.isnan(arr)
nan_check

array([False, False, False, False, False])

# **11. Input/Output**

In [52]:
# Save an array to a text file
np.savetxt('array.txt', arr)

In [53]:
# Load data from a text file
loaded_arr = np.loadtxt('array.txt')
loaded_arr

array([1., 2., 3., 4., 5.])

# **12. Date and Time Functions**

In [51]:
# Create datetime arrays
dates = np.array(['2021-01-01', '2022-01-01'], dtype='datetime64')
dates

array(['2021-01-01', '2022-01-01'], dtype='datetime64[D]')