# **1. Array Creation**

In [74]:
import numpy as np

In [75]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [76]:
# Create an array filled with zeros
zeros_arr = np.zeros((3, 3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
# Create an array filled with ones
ones_arr = np.ones((2, 4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
# Create an array filled with a specific value
full_arr = np.full((2, 3), 7)
full_arr

array([[7, 7, 7],
       [7, 7, 7]])

In [79]:
# Create an identity matrix
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
# Create an array with evenly spaced values within a given range
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [81]:
# Create an array with evenly spaced numbers over a specified interval
linspace_arr = np.linspace(0, 1, 5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [82]:
# Create an array with values that are logarithmically spaced
logspace_arr = np.logspace(0, 3, 4)
logspace_arr

array([   1.,   10.,  100., 1000.])

In [83]:
# Generate coordinate matrices from coordinate vectors
x, y = np.meshgrid(np.arange(3), np.arange(3))
print(x)
print(y)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [84]:
# Create an array with random values between 0 and 1
random_arr = np.random.rand(3, 3)
random_arr

array([[0.21681729, 0.57219943, 0.52424318],
       [0.55305569, 0.40923924, 0.90772444],
       [0.29417166, 0.32312952, 0.37142785]])

In [85]:
# Create an array with samples from the standard normal distribution
randn_arr = np.random.randn(3, 3)
randn_arr

array([[-0.53127806,  1.03374719,  0.75394304],
       [ 0.78183926,  1.11610026,  0.15762432],
       [ 1.08956517,  0.47556415,  0.37315679]])

In [86]:
# Create an array with random integers
randint_arr = np.random.randint(0, 10, (3, 3))
randint_arr

array([[4, 9, 9],
       [6, 4, 4],
       [8, 6, 9]])

# **2. Array Manipulation**

In [87]:
# Reshape the array
reshaped_arr = arr.reshape((5, 1))
reshaped_arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [88]:
# Flatten the array
flattened_arr = reshaped_arr.ravel()
flattened_arr

array([1, 2, 3, 4, 5])

In [89]:
# Transpose the array
transposed_arr = np.transpose(reshaped_arr)
transposed_arr

array([[1, 2, 3, 4, 5]])

In [90]:
# Swap two axes of an array
swapped_arr = np.swapaxes(zeros_arr, 0, 1)
swapped_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
# Join two or more arrays along an axis
concatenated_arr = np.concatenate((arr, arr))
concatenated_arr

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [92]:
# Stack arrays along a new axis
stacked_arr = np.stack((arr, arr))
stacked_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [93]:
# Split the array into multiple sub-arrays
split_arr = np.split(arr, 5)
split_arr

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [94]:
# Construct an array by repeating it
tiled_arr = np.tile(arr, 2)
tiled_arr

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [95]:
# Repeat elements of an array
repeated_arr = np.repeat(arr, 2)
repeated_arr

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [96]:
# Append values to the end of an array
appended_arr = np.append(arr, [4, 5, 6])
appended_arr

array([1, 2, 3, 4, 5, 4, 5, 6])

In [97]:
# Insert values into an array
inserted_arr = np.insert(arr, 1, [10])
inserted_arr

array([ 1, 10,  2,  3,  4,  5])

In [98]:
# Delete elements from an array
deleted_arr = np.delete(arr, [1])
deleted_arr

array([1, 3, 4, 5])

In [99]:
# Expand the dimensions of an array
expanded_arr = np.expand_dims(arr, axis=0)
expanded_arr

array([[1, 2, 3, 4, 5]])

In [100]:
# Remove single-dimensional entries from the shape of an array
squeezed_arr = np.squeeze(expanded_arr)
squeezed_arr

array([1, 2, 3, 4, 5])

In [101]:
# Reverse the order of elements in an array
flipped_arr = np.flip(arr)
flipped_arr

array([5, 4, 3, 2, 1])

In [102]:
# Expand dimensions
expanded_arr = np.expand_dims(arr, axis=1)
expanded_arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [103]:
# Squeeze dimensions
squeezed_arr = np.squeeze(expanded_arr)
squeezed_arr

array([1, 2, 3, 4, 5])

# **3. Array Operations**

In [104]:
# Element-wise addition
add_arr = np.add(arr, arr)
add_arr

array([ 2,  4,  6,  8, 10])

In [105]:
# Element-wise subtraction
sub_arr = np.subtract(arr, arr)
sub_arr

array([0, 0, 0, 0, 0])

In [106]:
# Element-wise multiplication
mul_arr = np.multiply(arr, arr)
mul_arr

array([ 1,  4,  9, 16, 25])

In [107]:
# Element-wise division
div_arr = np.divide(arr, arr)
div_arr

array([1., 1., 1., 1., 1.])

In [108]:
# Raise elements of the array to powers
pow_arr = np.power(arr, 2)
pow_arr

array([ 1,  4,  9, 16, 25])

In [109]:
# Dot product of two arrays
dot_product = np.dot(arr, arr)
dot_product

55

In [110]:
# Matrix product of two arrays
matmul_arr = np.matmul(arr, arr)
matmul_arr

55

In [111]:
# Inner product of two arrays
inner_arr = np.inner(arr, arr)
inner_arr

55

In [112]:
# Outer product of two arrays
outer_arr = np.outer(arr, arr)
outer_arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [113]:
# Kronecker product of two arrays
kron_arr = np.kron(arr, arr)
kron_arr

array([ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  3,  6,  9, 12, 15,  4,  8,
       12, 16, 20,  5, 10, 15, 20, 25])

In [114]:
# Compute the mean of array elements
mean_value = np.mean(arr)
mean_value

3.0

In [115]:
# Compute the standard deviation of array elements
std_value = np.std(arr)
std_value

1.4142135623730951

In [116]:
# Compute the variance of array elements
var_value = np.var(arr)
var_value

2.0

In [117]:
# Sum of array elements
sum_value = np.sum(arr)
sum_value

15

In [118]:
# Product of array elements
prod_value = np.prod(arr)
prod_value

120

In [119]:
# Cumulative sum of array elements
cumsum_value = np.cumsum(arr)
cumsum_value

array([ 1,  3,  6, 10, 15])

In [120]:
# Cumulative product of array elements
cumprod_value = np.cumprod(arr)
cumprod_value

array([  1,   2,   6,  24, 120])

In [121]:
# Minimum of array elements
min_value = np.min(arr)
min_value

1

In [122]:
# Maximum of array elements
max_value = np.max(arr)
max_value

5

In [123]:
# Index of the minimum element
argmin_value = np.argmin(arr)
argmin_value

0

In [124]:
# Index of the maximum element
argmax_value = np.argmax(arr)
argmax_value

4

In [125]:
# Sort the array elements
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [126]:
# Indices that would sort the array
argsort_arr = np.argsort(arr)
argsort_arr

array([0, 1, 2, 3, 4])

In [127]:
# Median of array elements
median_value = np.median(arr)
median_value

3.0

In [128]:
# Percentile of array elements
percentile_value = np.percentile(arr, 50)
percentile_value

3.0

# **4. Linear Algebra**

In [129]:
# Compute the inverse of a matrix
matrix = np.array([[1, 2], [3, 4]])
inv_matrix = np.linalg.inv(matrix)
inv_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [130]:
# Compute the determinant of a matrix
det_value = np.linalg.det(matrix)
det_value

-2.0000000000000004

In [131]:
# Compute the eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [132]:
# Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(matrix)
print(U)
print(S)
print(V)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[5.4649857  0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [133]:
# Compute the matrix or vector norm
norm_value = np.linalg.norm(matrix)
norm_value

5.477225575051661

In [134]:
# Solve a linear matrix equation
sol = np.linalg.solve(matrix, np.array([1, 2]))
sol

array([0. , 0.5])

In [135]:
# Solve a linear least squares problem
lstsq_sol = np.linalg.lstsq(matrix, np.array([1, 2]), rcond=None)
lstsq_sol

(array([1.10886662e-16, 5.00000000e-01]),
 array([], dtype=float64),
 2,
 array([5.4649857 , 0.36596619]))

# **5. Fourier Transform**

In [ ]:
# One-dimensional discrete Fourier Transform
fft_result = np.fft.fft(arr)
fft_result

array([15. +0.j        , -2.5+3.4409548j , -2.5+0.81229924j,
       -2.5-0.81229924j, -2.5-3.4409548j ])

In [ ]:
# Inverse discrete Fourier Transform
ifft_result = np.fft.ifft(fft_result)
ifft_result

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [136]:
# Compute the two-dimensional discrete Fourier Transform
fft2_arr = np.fft.fft2(identity_matrix)
fft2_arr

array([[4.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 4.+0.j],
       [0.+0.j, 0.+0.j, 4.+0.j, 0.+0.j],
       [0.+0.j, 4.+0.j, 0.+0.j, 0.+0.j]])

In [137]:
# Compute the two-dimensional inverse discrete Fourier Transform
ifft2_arr = np.fft.ifft2(fft2_arr)
ifft2_arr

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

# **6. Random Number Generation**

In [ ]:
# Generate random floats
random_floats = np.random.random((2, 2))
random_floats

array([[0.50431659, 0.47354234],
       [0.13086532, 0.56782472]])

In [140]:
# Seed the random number generator
np.random.seed(42)

In [ ]:
# Generate random integers
random_integers = np.random.randint(0, 10, (2, 2))
random_integers

array([[9, 9],
       [6, 3]])

In [141]:
# Generate a random sample from a given 1-D array
random_sample = np.random.choice(arr, 2)
random_sample

array([4, 5])

In [142]:
# Randomly permute a sequence or return a permuted range
permuted_arr = np.random.permutation(arr)
permuted_arr

array([2, 5, 1, 4, 3])

In [145]:
# Modify a sequence in place by shuffling its contents
np.random.shuffle(arr)
arr

array([4, 3, 2, 1, 5])

# **7. Statistics and Probability**

In [146]:
# Compute the arithmetic mean along the specified axis
mean_value = np.mean(arr)
mean_value

3.0

In [41]:
# Compute the median
median_value = np.median(arr)
median_value

3.0

In [42]:
# Compute the standard deviation
std_dev = np.std(arr)
std_dev

1.4142135623730951

In [43]:
# Compute the variance
variance = np.var(arr)
variance

2.0

In [44]:
# Generate a histogram of data
hist, bin_edges = np.histogram(arr)
print(hist)
print(bin_edges)

[1 0 1 0 0 1 0 1 0 1]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


In [147]:
# Compute the nth percentile of the array elements
percentile_value = np.percentile(arr, 50)
percentile_value

3.0

In [148]:
# Return Pearson product-moment correlation coefficients
corrcoef_arr = np.corrcoef(arr, arr)
corrcoef_arr

array([[1., 1.],
       [1., 1.]])

In [150]:
# Estimate a covariance matrix
cov_arr = np.cov(arr)
cov_arr

array(2.5)

# **8. Trigonometric Functions**

In [ ]:
# Compute the sine
sine_values = np.sin(arr)
sine_values

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
# Compute the cosine
cosine_values = np.cos(arr)
cosine_values

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
# Compute the tangent
tangent_values = np.tan(arr)
tangent_values

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [151]:
# Compute the inverse sine
arcsine_arr = np.arcsin(arr)
arcsine_arr

<ipython-input-151-3f783bf95108>:2: RuntimeWarning: invalid value encountered in arcsin
  arcsine_arr = np.arcsin(arr)


array([       nan,        nan,        nan, 1.57079633,        nan])

In [152]:
# Compute the inverse cosine
arccosine_arr = np.arccos(arr)
arccosine_arr

<ipython-input-152-5d5dd3604a69>:2: RuntimeWarning: invalid value encountered in arccos
  arccosine_arr = np.arccos(arr)


array([nan, nan, nan,  0., nan])

In [153]:
# Compute the inverse tangent
arctangent_arr = np.arctan(arr)
arctangent_arr

array([1.32581766, 1.24904577, 1.10714872, 0.78539816, 1.37340077])

In [154]:
# Compute the element-wise arc tangent of y/x
arctan2_arr = np.arctan2(arr, arr)
arctan2_arr

array([0.78539816, 0.78539816, 0.78539816, 0.78539816, 0.78539816])

In [155]:
# Compute the hyperbolic sine
sinh_arr = np.sinh(arr)
sinh_arr

array([27.2899172 , 10.01787493,  3.62686041,  1.17520119, 74.20321058])

In [156]:
# Compute the hyperbolic cosine
cosh_arr = np.cosh(arr)
cosh_arr

array([27.30823284, 10.067662  ,  3.76219569,  1.54308063, 74.20994852])

In [157]:
# Compute the hyperbolic tangent
tanh_arr = np.tanh(arr)
tanh_arr

array([0.9993293 , 0.99505475, 0.96402758, 0.76159416, 0.9999092 ])

In [158]:
# Compute the inverse hyperbolic sine
arcsinh_arr = np.arcsinh(arr)
arcsinh_arr

array([2.09471255, 1.81844646, 1.44363548, 0.88137359, 2.31243834])

In [160]:
# Compute the inverse hyperbolic cosine
arccosh_arr = np.arccosh(arr)
arccosh_arr

array([2.06343707, 1.76274717, 1.3169579 , 0.        , 2.29243167])

In [161]:
# Compute the inverse hyperbolic tangent
arctanh_arr = np.arctanh(arr)
arctanh_arr

<ipython-input-161-6c27f2b26f96>:2: RuntimeWarning: divide by zero encountered in arctanh
  arctanh_arr = np.arctanh(arr)
<ipython-input-161-6c27f2b26f96>:2: RuntimeWarning: invalid value encountered in arctanh
  arctanh_arr = np.arctanh(arr)


array([nan, nan, nan, inf, nan])

In [162]:
# Convert degrees to radians
radians_arr = np.deg2rad(arr)
radians_arr

array([0.06981317, 0.05235988, 0.03490659, 0.01745329, 0.08726646])

In [163]:
# Convert radians to degrees
degrees_arr = np.rad2deg(arr)
degrees_arr

array([229.18311805, 171.88733854, 114.59155903,  57.29577951,
       286.47889757])

# **9. Exponential and Logarithmic Functions**

In [ ]:
# Compute the exponential
exp_values = np.exp(arr)
exp_values

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [164]:
# Compute exp(x) - 1 for all elements in the array
expm1_arr = np.expm1(arr)
expm1_arr

array([ 53.59815003,  19.08553692,   6.3890561 ,   1.71828183,
       147.4131591 ])

In [ ]:
# Compute the natural logarithm
log_values = np.log(arr)
log_values

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
# Compute the base-10 logarithm
log10_values = np.log10(arr)
log10_values

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [165]:
# Compute the base-2 logarithm of all elements in the array
log2_arr = np.log2(arr)
log2_arr

array([2.        , 1.5849625 , 1.        , 0.        , 2.32192809])

In [166]:
# Compute log(1 + x) for all elements in the array
log1p_arr = np.log1p(arr)
log1p_arr

array([1.60943791, 1.38629436, 1.09861229, 0.69314718, 1.79175947])

# **10. Miscellaneous**

In [ ]:
# Copy an array
copied_arr = np.copy(arr)
copied_arr

array([1, 2, 3, 4, 5])

In [ ]:
# Find the unique elements of an array
unique_elements = np.unique(arr)
unique_elements

array([1, 2, 3, 4, 5])

In [ ]:
# Test for NaN values
nan_check = np.isnan(arr)
nan_check

array([False, False, False, False, False])

In [167]:
# Test element-wise for finiteness
is_finite = np.isfinite(arr)
is_finite

array([ True,  True,  True,  True,  True])

In [168]:
# Test element-wise for infinity
is_infinite = np.isinf(arr)
is_infinite

array([False, False, False, False, False])

In [169]:
# Test element-wise for NaN
is_nan = np.isnan(arr)
is_nan

array([False, False, False, False, False])

In [170]:
# Return a new array with the same shape and type as a given array, without initializing entries
empty_like_arr = np.empty_like(arr)
empty_like_arr

array([4609927083155361075, 4608922133940812271, 4607626529066517258,
       4604418534313441775, 4610748186450599938])

In [171]:
# Return an array of zeros with the same shape and type as a given array
zeros_like_arr = np.zeros_like(arr)
zeros_like_arr

array([0, 0, 0, 0, 0])

In [172]:
# Return an array of ones with the same shape and type as a given array
ones_like_arr = np.ones_like(arr)
ones_like_arr

array([1, 1, 1, 1, 1])

# **11. Input/Output**

In [179]:
# Save and load arrays from text files
np.savetxt("array.txt", arr)
loaded_arr = np.loadtxt("array.txt")
loaded_arr

array([4., 3., 2., 1., 5.])

In [180]:
# Save and load arrays from binary files
np.save("array.npy", arr)
loaded_binary_arr = np.load("array.npy")
loaded_binary_arr

array([4, 3, 2, 1, 5])

In [181]:
# Save several arrays into a single .npz file
np.savez("arrays.npz", arr1=arr, arr2=arr)
loaded_npz = np.load("arrays.npz")
arr1 = loaded_npz['arr1']
arr2 = loaded_npz['arr2']
print(arr1)
print(arr2)

[4 3 2 1 5]
[4 3 2 1 5]


In [183]:
# Load data from a text file with missing values handled as specified
data = np.genfromtxt("array.txt", delimiter=',')
data

array([4., 3., 2., 1., 5.])

# **12. Date and Time Functions**

In [175]:
# Create datetime arrays
dates = np.array(['2021-01-01', '2022-01-01'], dtype='datetime64')
dates

array(['2021-01-01', '2022-01-01'], dtype='datetime64[D]')

In [176]:
# Create an array of time differences
time_deltas = np.array([1, 2], dtype='timedelta64[D]')
time_deltas

array([1, 2], dtype='timedelta64[D]')

In [177]:
# Convert datetime64 to string
date_strings = np.datetime_as_string(dates)
date_strings

array(['2021-01-01', '2022-01-01'], dtype='<U28')

# **13. Other Mathematical Functions**

In [190]:
# Compute the square root of all elements in the array
sqrt_arr = np.sqrt(arr)
sqrt_arr

array([2.        , 1.73205081, 1.41421356, 1.        , 2.23606798])

In [191]:
# Compute the square of all elements in the array
square_arr = np.square(arr)
square_arr

array([16,  9,  4,  1, 25])

In [192]:
# Compute the absolute value element-wise
absolute_arr = np.absolute(arr)
absolute_arr

array([4, 3, 2, 1, 5])

In [193]:
# Returns an element-wise indication of the sign of a number
sign_arr = np.sign(arr)
sign_arr

array([1, 1, 1, 1, 1])

In [194]:
# Return the ceiling of the input, element-wise
ceil_arr = np.ceil(arr)
ceil_arr

array([4., 3., 2., 1., 5.])

In [195]:
# Return the floor of the input, element-wise
floor_arr = np.floor(arr)
floor_arr

array([4., 3., 2., 1., 5.])

In [196]:
# Round elements of the array to the nearest integer
round_arr = np.round(arr)
round_arr

array([4, 3, 2, 1, 5])

In [197]:
# Round elements to the nearest integer, returning the result as a float
rint_arr = np.rint(arr)
rint_arr

array([4., 3., 2., 1., 5.])

In [198]:
# Element-wise remainder of division
mod_arr = np.mod(arr, 2)
mod_arr

array([0, 1, 0, 1, 1])

In [199]:
# Clip (limit) the values in an array
clipped_arr = np.clip(arr, 1, 3)
clipped_arr

array([3, 3, 2, 1, 3])

# **14. Logical Operations**

In [200]:
# Test whether all array elements evaluate to True
all_true = np.all(arr > 0)
all_true

True

In [201]:
# Test whether any array element evaluates to True
any_true = np.any(arr > 0)
any_true

True

In [202]:
# Compute the element-wise logical AND
logical_and_arr = np.logical_and(arr > 0, arr < 3)
logical_and_arr

array([False, False,  True,  True, False])

In [203]:
# Compute the element-wise logical OR
logical_or_arr = np.logical_or(arr > 0, arr < 3)
logical_or_arr

array([ True,  True,  True,  True,  True])

In [204]:
# Compute the element-wise logical NOT
logical_not_arr = np.logical_not(arr > 0)
logical_not_arr

array([False, False, False, False, False])

In [206]:
# Compute the element-wise logical XOR
logical_xor_arr = np.logical_xor(arr > 0, arr < 3)
logical_xor_arr

array([ True,  True, False, False,  True])

In [207]:
# Return elements chosen from x or y depending on condition
where_arr = np.where(arr > 2, arr, -1)
where_arr

array([ 4,  3, -1, -1,  5])

In [208]:
# Return an array drawn from elements in choices based on conditions
conditions = [arr < 1, arr > 2]
choices = [0, 10]
select_arr = np.select(conditions, choices, default=-1)
select_arr

array([10, 10, -1, -1, 10])